Repository SRTigers98/birthday-discord-bot, pull requests merged in 2022-03, with the labels that each got.

#1 feature/javadoc
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/BirthdayDiscordBotApplication.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdayCommand.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdayDeleteCommand.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdaySaveCommand.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdaySelectCommand.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdayShowCommand.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/config/DiscordConfiguration.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/dao/BirthdayRepository.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/dao/GuildConfigRepository.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/dto/Birthday.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/dto/BirthdayId.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/dto/GuildConfig.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/exception/BirthdayExceptions.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/BirthdayService.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/GuildConfigService.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/ReminderService.kt
Labels: documentation

#6 Feature/Basic logging
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/BirthdayDiscordBotApplication.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/BirthdayService.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/GuildConfigService.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/ReminderService.kt
Labels: documentation, enhancement

#11 Feature/version-command
  .github/workflows/build.yml
  Dockerfile
  build.gradle.kts
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdayCommand.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdayDeleteCommand.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdaySaveCommand.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdaySelectCommand.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdayShowCommand.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdayVersionCommand.kt
  src/test/kotlin/io/github/srtigers98/birthdaydiscordbot/application/command/BirthdayVersionCommandTest.kt
Labels: enhancement

#12 Feature/startup-refactoring
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/BirthdayDiscordBotApplication.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/config/DiscordCommandConfiguration.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/config/DiscordConfiguration.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/listener/CommandListener.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/listener/KordListener.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/run/BotStartupRunner.kt
  src/test/kotlin/io/github/srtigers98/birthdaydiscordbot/application/listener/CommandListenerTest.kt
  src/test/kotlin/io/github/srtigers98/birthdaydiscordbot/application/run/BotStartupRunnerIntegrationTest.kt
Labels: refactor

#13 Feature/garbage-collection
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/CleanupService.kt
  src/main/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/GuildConfigService.kt
  src/test/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/CleanupServiceTest.kt
  src/test/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/GuildConfigServiceIntegrationTest.kt
  src/test/kotlin/io/github/srtigers98/birthdaydiscordbot/application/service/GuildConfigServiceTest.kt
Labels: enhancement

#17 Feature/community-standards
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#19 Feature/test-build
  .github/workflows/analyze.yml
  .github/workflows/build.yml
  build.gradle.kts
Labels: build
